### ISSUE TITLE
Searching for "am" shows 🇺🇲 result twice

### ISSUE THREAD

**Issue by chetbox** [chetbox/Emojikey#8]
![screen shot 2016-09-17 at 21 47 43](https://cloud.githubusercontent.com/assets/292958/18610884/6600e114-7d20-11e6-9ba4-edc3e63bf73d.png)

**Comment by hermzz** [comment]
They're technically two different countries, United States and U.S. Outlying Islands. Also, doesn't happen any more with a fresh `emoji-data.json` file.

**Comment by chetbox** [comment]
Amazing.
